command: ["python", "backend/main.py"]

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: 152b63ead0b2ebfb

app_accesses:
  - api_scopes:
      - jobs:read
      - unity-catalog:read    # needed for UC REST API
